name: Deploy Static HTML to Walrus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy site to Walrus
        uses: zktx-io/walrus-sites-ga@v0.3.4
        with:
          site-path: '.' #  For static HTML, the site path is likely the root
          network: 'testnet' # Or 'mainnet'
          epochs: 183 # Adjust as needed
          object-id: '0x1a64a12447b5581ba4dd40cb0cd8f9bb485a7db3b42789158e467e5e5c531af8' # Your object ID
          wal-exchange-enabled: false # Adjust as needed
        env:
          SUI_ADDRESS: ${{ vars.SUI_PUBLIC_ADDRESS }} # Your Sui public address
          SUI_KEYSTORE: ${{ secrets.SUI_PRIVATE_KEY }} # Your Sui private key (stored as a secret)
